import typing as ty
import pandas as pd

# pj imports
import phylojunction.pgm.pgm as pgm
import phylojunction.data.tree as AnnotatedTree

def read_text_file(fp_string: str) -> ty.List[str]: ...
def read_serialized_pgm(fp_string: str) -> pgm.DirectedAcyclicGraph: ...
def read_csv_tsv_into_dataframe(fp_string: str) -> pd.DataFrame: ...
def is_csv(fp_string: str) -> bool: ...
def parse_cli_str_write_fig(str_write_fig: str) -> ty.Dict[str, ty.Tuple[int]]: ...
def read_nwk_tree_str(nwk_tree_path_or_str: str, fn_name: str, in_file: bool=True, node_names_attribute: str="", epsilon: float=1e-12) -> AnnotatedTree: ...
def read_node_attr_update_tree(attr_tsv_fp: str, attr_name: str, ann_tr: AnnotatedTree) -> None: ...