import pgm.pgm as pgm

def script2pgm(file_handle) -> None: ...
def cmdline2pgm(pgm_obj: pgm.ProbabilisticGraphicalModel, cmd_line: str): ...
def parse_variable_assignment(pgm_obj: pgm.ProbabilisticGraphicalModel, stoch_node_name: str, stoch_node_spec: str, cmd_line: str) -> None: ...
def parse_samp_dn_assignment(pgm_obj, stoch_node_name, stoch_node_dn_spec, cmd_line) -> None: ...
def parse_deterministic_function_assignment(pgm_obj: pgm.ProbabilisticGraphicalModel, det_nd_name: str, det_fn_spec: str, cmd_line: str) -> None: ...
