import typing as ty

import phylojunction.pgm.pgm as pgm

def script2dag(script_file_path: str, in_pj_file: bool=True, random_seed: ty.Optional[int]=None) -> pgm.DirectedAcyclicGraph: ...
def cmdline2dag(dag_obj: pgm.DirectedAcyclicGraph, cmd_line: str): ...
def parse_variable_assignment(dag_obj: pgm.DirectedAcyclicGraph, stoch_node_name: str, stoch_node_spec: str, cmd_line: str) -> None: ...
def parse_samp_dn_assignment(dag_obj, stoch_node_name, stoch_node_dn_spec, cmd_line) -> None: ...
def parse_deterministic_function_assignment(dag_obj: pgm.DirectedAcyclicGraph, det_nd_name: str, det_fn_spec: str, cmd_line: str) -> None: ...
