import typing as ty

def print_progress(idx: int, iterator_len: int) -> None: ...
def autovivify(levels: int = ..., final=...) -> ty.DefaultDict: ...
def verify_or_convert2_vector(param_list, dn_name, size_to_grow: int = ...) -> ty.List[ty.List[ty.Union[int, float, str]]]: ...
def get_ellapsed_time_in_minutes(start: float, end: float) -> int: ...
