import phylojunction.pgm.pgm as pgm
import phylojunction.calculation.discrete_sse as sseobj
import typing as ty

def make_DiscreteStateDependentRate(det_fn_param_dict: ty.Dict[str, ty.List[ty.Union[str, pgm.NodeDAG]]]) -> sseobj.DiscreteStateDependentRate: ...
def make_DiscreteStateDependentProbability(det_fn_param_dict: ty.Dict[str, ty.List[ty.Union[str, pgm.NodeDAG]]]) -> sseobj.DiscreteStateDependentProbability: ...
def make_SSEStash(det_fn_param_dict: ty.Dict[str, ty.List[ty.Union[str, pgm.NodeDAG]]]) -> sseobj.SSEStash: ...
